---
- name: Adding Admin Users
  uri:
    url: https://{{ nextlinux_api_url }}/v1/accounts/admin/users
    user: admin
    password: "{{ admin_pass }}"
    headers:
      Content-Type: application/json
      x-nextlinux-account: admin
      x-nextlinux-authz-action: createUser
    method: POST
    body:
      username: "{{ item.name }}"
      password: "{{ item.password }}"
    force_basic_auth: yes
    validate_certs: no
    body_format: json
    status_code: [200, 400, 500]
  ignore_errors: true
  no_log: true
  register: add_admin_users
  with_items: "{{ admin_users }}"